// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZsEqTz6g_o6ySmWDTl-jbOSuufM0ZYto',
    appId: '1:843421365844:web:c7d43f13e5797e32b35fc1',
    messagingSenderId: '843421365844',
    projectId: 'ai-career-assistant-de7d9',
    authDomain: 'ai-career-assistant-de7d9.firebaseapp.com',
    databaseURL: 'https://ai-career-assistant-de7d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-career-assistant-de7d9.firebasestorage.app',
    measurementId: 'G-B2FXPYLSBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNuexn1kOAWBKPA64MwCQLcjCAe2ax9g',
    appId: '1:843421365844:android:2fba36521c9e3640b35fc1',
    messagingSenderId: '843421365844',
    projectId: 'ai-career-assistant-de7d9',
    databaseURL: 'https://ai-career-assistant-de7d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-career-assistant-de7d9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgpY96ncoJbSv14xnjprJN-24qORA-WQ',
    appId: '1:843421365844:ios:5cac32c9ffc236cfb35fc1',
    messagingSenderId: '843421365844',
    projectId: 'ai-career-assistant-de7d9',
    databaseURL: 'https://ai-career-assistant-de7d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-career-assistant-de7d9.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOgpY96ncoJbSv14xnjprJN-24qORA-WQ',
    appId: '1:843421365844:ios:5cac32c9ffc236cfb35fc1',
    messagingSenderId: '843421365844',
    projectId: 'ai-career-assistant-de7d9',
    databaseURL: 'https://ai-career-assistant-de7d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-career-assistant-de7d9.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZsEqTz6g_o6ySmWDTl-jbOSuufM0ZYto',
    appId: '1:843421365844:web:b988e435572fbb71b35fc1',
    messagingSenderId: '843421365844',
    projectId: 'ai-career-assistant-de7d9',
    authDomain: 'ai-career-assistant-de7d9.firebaseapp.com',
    databaseURL: 'https://ai-career-assistant-de7d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-career-assistant-de7d9.firebasestorage.app',
    measurementId: 'G-SPMYGGMB9R',
  );
}
